plugins {
    id 'com.android.application'
}

android {
    namespace 'globus.demo'
    compileSdk sdk_version
    ndkVersion rootProject.ext.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    defaultConfig {
        applicationId "globus.demo"
        minSdkVersion min_sdk_version
        targetSdkVersion sdk_version
        versionCode version_code
        versionName glmap_version
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    sourceSets {
        main {
            assets.srcDirs = ["src/main/assets", "../../../Resources/framework"]
        }
    }

    // If world and font files are compressed - GLMap will decompress and cache them during initialization.
    // This will take some time and space on device.
    // You can disable compression for them in resulting apk file to speedup loading time.
    androidResources {
        noCompress 'vm', 'ttf', 'otf'
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:$app_compat_version"
    implementation "com.google.android.gms:play-services-location:$gms_location_version"
    androidTestImplementation "androidx.test.ext:junit:1.3.0"
    androidTestImplementation "androidx.test:runner:1.7.0"

    if (rootProject.ext.useLocalGLMap) {
        implementation project(':glmap')
        implementation project(':glroute')
        implementation project(':glsearch')
    } else {
        implementation "globus:glmap:$glmap_version"
        implementation "globus:glroute:$glmap_version"
        implementation "globus:glsearch:$glmap_version"
    }
}
